services:
  frontend:
    image: ghcr.io/acts-se-2026/the-game-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    
 
  backend:
    image: ghcr.io/acts-se-2026/the-game-backend:latest
    restart: unless-stopped

    volumes:
      - .env.backend:/build/.env
      
